---
title: "PUBH 7462 - Homework 1"
author: "Maykon da Silva"
date: "1/30/2022"
output: html_document
---

```{r setup, include = FALSE}
#Load all the good stuff
library(tidyverse)

#Working directory for .RMD
knitr::opts_knit$set(echo = TRUE,
                     root.dir = rprojroot::find_rstudio_root_file())

#Controlling figure output in markdown
knitr::opts_chunk$set(
#  fig.height =   
  fig.width = 6,
#  fig.asp = .5,
  out.width = "90%",
#  out.height = 
 fig.align = "center",
  cache = FALSE,
  echo  = TRUE
)

#Set Theme for ggplot2 - centers title and legend at bottom by default
theme_set(theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom"))

#Set Scientific notation output and decimal places for knitr
options(scipen = 999)
options(digits = 4)
```

# 1. Main Heading

## 1.1 Subheading  

### 1.1.1 Sub-subheading  

- List  
    - *italics*  
    - **bold**  
    
1. Numbered list  
    - Bullet  
    2. Number  
    
### 1.1.2 R chunk  

```{r chunk_ex, echo = TRUE, warning = TRUE, error = TRUE, message = TRUE, results = TRUE, include = TRUE}
#Store object
eulers_no <- exp(1)
```

### 1.2.3 Inline R

Given the `options(digits = 4)` in the setup R chunk, it follows that the 4 digits approximation to Euler's number ($e$) can be expressed with inline R as $e \approx$ `r eulers_no`. 